export const GET_CASES_WORLDWIDE_SUCCESS = "GET_CASES_WORLDWIDE_SUCCESS";
export const GET_CASES_WORLDWIDE_FAILED = "GET_CASES_WORLDWIDE_FAILED";

export const GET_LIST_BY_COUNTRY_SUCCESS = "GET_LIST_BY_COUNTRY_SUCCESS";
export const GET_CASES_BY_COUNTRY_SUCCESS = "GET_CASES_BY_COUNTRY_SUCCESS";
